#############################################################
# Equilibration
#############################################################
set topfile             /home/ctang/1.Ongoing/1.Diffusion.Additional/4.VoDomain/TOP_files
set outputname          Unbiased.A

# MD steps
numSteps                1

# System
structure		$topfile/input.psf
coordinates		$topfile/input.pdb
bincoordinates		TMD.A.coor
extendedSystem 		TMD.A.xsc

# Output
outputName              Unbiased.A
restartfreq		5000	
dcdfreq			5000
xstFreq			5000
outputEnergies		5000
outputPressure		5000

# Temperature
set temperature		310.0

# PBC
wrapWater		on
wrapAll			on

# Force field
paraTypeCharmm		on
parameters		$topfile/toppar/par_all36m_prot.prm
parameters		$topfile/toppar/par_all36_lipid.prm
parameters		$topfile/toppar/par_all36_na.prm
parameters		$topfile/toppar/par_all36_carb.prm
parameters		$topfile/toppar/par_all36_cgenff.prm
parameters		$topfile/toppar/toppar_water_ions.str
parameters		$topfile/toppar/toppar_all36_carb_glycolipid.str
exclude			scaled1-4
1-4scaling		1.0
switching		on
vdwForceSwitching	on
cutoff			12.0
switchdist		10.0
pairlistdist		14.0

# Multiple time-stepping
timestep		2.0 
rigidBonds		all
nonbondedFreq		1
fullElectFrequency	4
splitpatch		hydrogen
hgroupcutoff		2.8

# PME
PME                 	yes
PMEGridSpacing      	1.2

# Constant Temperature Control
temperature		$temperature
langevin		on  
langevinDamping		0.1 
langevinTemp		$temperature
langevinHydrogen	no   

# Constant Pressure Control (variable volume)
langevinPiston		on
langevinPistonTarget	1.0
langevinPistonPeriod	300.0
langevinPistonDecay	200.0
langevinPistonTemp	$temperature
useGroupPressure	yes 
useFlexibleCell		yes
useConstantRatio        no 
useConstantArea		no 

dcdSelection           yes
dcdSelectionInputfile  soluteonly index.noh.pdb
dcdSelectionfreq       soluteonly 100
dcdSelectionfile       soluteonly $outputname.noh.dcd

colvars                 on
colvarsConfig           colvars.in

GPUResident             on
run    1000000
