
timestep	0.5
set inputname ./TOP_files

structure	$inputname/alad.psf
coordinates	$inputname/A.pdb
#bincoordinates  min.coor
temperature     300.0

outputname      TMD.A

# DCD FILE

dcdFile         TMD.A.dcd


# FREQUENCY FOR DUMPING OUTPUT DATA

outputenergies  1000
outputtiming    1000
outputpressure  1000
restartfreq     1000 
XSTFreq         100
dcdFreq         100

margin		10.0
stepspercycle	20
paraTypeCharmm	on
parameters	$inputname/par_all22_prot.prm
exclude		scaled1-4
1-4scaling	1.0
switching 	on
switchdist      16.0
cutoff          18.0
pairlistdist    20.0

langevin	on
langevinDamping	1.0
langevinTemp    300.0
                
colvars         on
colvarsConfig   "colvars.in"

TMD             on
TMDk            500.0
TMDFile         output.pdb
TMDLastStep     20000
TMDOutputFreq   100

firsttimestep   0
run             20000
