##################################################
##################################################
#
# ABF calculation
#
# Deca-alanine
#
##################################################
##################################################


##################################################
# MD SECTION
##################################################

set outName          Unbias.B
set inputname        ./TOP_files/


# TOPOLOGY


# FORCE FIELD

parmfile             ${inputname}trialanine.parm7


# INPUT FILES

#coordinates          minimize.coor
coordinates          ${inputname}B.pdb
binvelocities        TMD.B.restart.vel
bincoordinates       TMD.B.restart.coor
## SIMULATION PARAMETERS                                  
# AMBER FF settings
amber               on

cutoff              9.0
pairlistdist        11.0
switching           off
exclude             scaled1-4
readexclusions      yes
1-4scaling          0.83333333

scnb                2.0
zeromomentum        on
ljcorrection        off
watermodel          tip3

nonbondedFreq       1 
fullElectFrequency  1 

hgroupcutoff        2.8


# OUTPUT FILES

binaryoutput         no  
binaryrestart        yes

outputname           ${outName}
restartname          ${outName}.restart


# DCD FILE

dcdFile              ${outName}.dcd


# FREQUENCY FOR DUMPING OUTPUT DATA

outputenergies       100
outputtiming         10000
outputpressure       10000
restartfreq          10000 
XSTFreq              10000 
dcdFreq              100



# CONSTANT-T

langevin             on
langevintemp         300.0
langevindamping      1.0 


# MULTIPLE TIME-STEP PROPAGATOR

timestep             0.5


# SHAKE/RATTLE

rigidbonds           none


# PARALLELISM

stepspercycle        16
splitpatch           hydrogen
margin               2.0


# ABF SECTION

colvars              on
colvarsConfig        colvars.in

firsttimestep   0
run             2000000
